server:
  port: 8765
    
spring:   
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/lwb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
mybatis:
  mapper-locations: mapper/*.xml
