server:
  port: 8766
    
spring:   
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/lwb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
mybatis:
  mapper-locations: mapper/*.xml





eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka